title: Ankur Mahajan
logo: "/ankur.jpeg?raw=true"
description: >
Technical Architect
<br><br>
<a href="mailto:ankur.mahajan@hotmail.com">Email me</a>
<br>
<a href="https://www.linkedin.com/in/ankur-mahajan-a5271415/">LinkedIn</a>

theme: jekyll-theme-minimal
