title: Ankur Mahajan
logo: "/ankur.jpeg?raw=true"
description: >
 <br>
 Technical Architect
  <br><br>
  <a href="mailto:mahajanankur.nith@gmail.com"><img align="center" src="https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/gmail.svg" alt="ankur-mahajan-a5271415" height="25" width="25" /></a>&nbsp;
  <a href="https://linkedin.com/in/ankur-mahajan-a5271415" target="blank"><img align="center" src="https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/linkedin.svg" alt="ankur-mahajan-a5271415" height="25" width="25" /></a>&nbsp;
  <a href="https://stackoverflow.com/users/3932396/ankur-mahajan" target="blank"><img align="center" src="https://cdn.jsdelivr.net/npm/simple-icons@3.0.1/icons/stackoverflow.svg" alt="https://stackoverflow.com/users/3932396/ankur-mahajan" height="25" width="25" /></a>&nbsp;
theme: jekyll-theme-minimal
